### ISSUE TITLE
Ugly code blocks

### ISSUE THREAD

**Issue by spond** [veg/hyphy-site#30]
Please note that current code blocks are rendered as 

```
<pre>
<code></code>
</pre>
```

which creates undesirable graduated shading two levels) and excessive padding. I personally would like to see code rendered like 

```
<pre style = 'font-family: courier; font-size: 12pt; color: #85274e; background-color: rgba(0,0,0,0.05)'>
LikelihoodFunction LF = (filter, tree);
</pre>
```
<img width="751" alt="screen shot 2017-03-30 at 10 03 10 pm" src="https://cloud.githubusercontent.com/assets/1018513/24535981/bca1076c-1594-11e7-86f7-05ccfdad5c4b.png">

**Comment by stevenweaver** [comment]
Thank you Sergei, I will take a look at this tomorrow morning.

**Comment by stevenweaver** [comment]
Hi Sergei, 

I think if we annotate the code blocks with ```js, the styling would look very close to what you are looking for out of the box.

Please see https://stevenweaver.github.io/hyphy-site/about/

**Comment by spond** [comment]
Dear @stevenweaver,

This is perfect. 

Best,
Sergei
